os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - 'lts/*'
services:
  - xvfb
before_script:
  - export DISPLAY=:99.0
script:
  - cd angular
  - npm install
  - npm run test
  - cd ../electron
  - npm install
  - npm run coverage # jest test with coverage flag does coverage too
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls' # sends the coverage report to coveralls
